# This is a basic workflow to help you get started with Actions

name: Backup Firestore

on:
  schedule:
    - cron:  '20 14 * * *'

env:
  PROJECT_ID: school-4f47a
  BUCKET: gs://backup-school-test
  
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - run: gcloud info
    - run: gcloud config set project $PROJECT_ID
    - run: gcloud firestore export $BUCKET
